/**
 * KARIGAR Artisanal Heritage Platform - Central Craft Image & Category Mapping
 * 
 * Maps every specific craftType to its parent Category and the corresponding
 * verified image asset from the existing /demo_image folder.
 */

export const craftCategoryMap = Object.freeze({
  "Jamdani": "Handloom & Textiles",
  "Jamdani Weave": "Handloom & Textiles",
  "Baluchari & Swarnachari": "Handloom & Textiles",
  "Kani Pashmina": "Handloom & Textiles",
  "Chanderi Weave": "Handloom & Textiles",
  "Banarasi Brocade": "Handloom & Textiles",
  "Tant": "Handloom & Textiles",
  "Patola": "Handloom & Textiles",
  "Bandhani": "Handloom & Textiles",
  "Sambalpuri Ikat": "Handloom & Textiles",
  "Muga Silk": "Handloom & Textiles",
  "Kanchipuram Silk": "Handloom & Textiles",
  "Banarasi": "Handloom & Textiles",
  "Kutch Embroidery": "Embroidery",
  "Phulkari": "Embroidery",
  "Chikankari": "Embroidery",
  "Kantha": "Embroidery",
  "Nakshi Kantha": "Embroidery",
  "Kasuti": "Embroidery",
  "Bankura Terracotta": "Pottery & Clay",
  "Krishnanagar Clay": "Pottery & Clay",
  "Khurja Pottery": "Pottery & Clay",
  "Blue Pottery": "Pottery & Clay",
  "Jaipur Blue Pottery": "Pottery & Clay",
  "Terracotta": "Pottery & Clay",
  "Clay Craft": "Pottery & Clay",
  "Regional Pottery": "Pottery & Clay",
  "Bengal Dhokra": "Metal & Dhokra",
  "Bastar Dhokra": "Metal & Dhokra",
  "Dhokra Jewellery": "Jewellery & Accessories",
  "Bell Metal Work": "Metal & Dhokra",
  "Tribal Metal Craft": "Metal & Dhokra",
  "Kalighat Painting": "Painting & Folk Art",
  "Pattachitra": "Painting & Folk Art",
  "Madhubani": "Painting & Folk Art",
  "Odisha Pattachitra": "Painting & Folk Art",
  "Phad Painting": "Painting & Folk Art",
  "Gond Painting": "Painting & Folk Art",
  "Warli Painting": "Painting & Folk Art",
  "Kundan Jewellery": "Jewellery & Accessories",
  "Meenakari Jewellery": "Jewellery & Accessories",
  "Tribal Jewellery": "Jewellery & Accessories",
  "Silver Filigree": "Jewellery & Accessories",
  "Traditional Jewellery": "Jewellery & Accessories",
  "Kundan": "Jewellery & Accessories",
  "Meenakari": "Jewellery & Accessories",
  "Silver Filigree Work": "Jewellery & Accessories",
  "Tribal Jewelry": "Jewellery & Accessories",
  "Jewellery": "Jewellery & Accessories",
  "Jewelry": "Jewellery & Accessories",
  "Jewellery & Accessories": "Jewellery & Accessories",
  "Jewelry & Accessories": "Jewellery & Accessories",
  "Bamboo Furniture": "Wood, Bamboo & Cane",
  "Cane Baskets": "Wood, Bamboo & Cane",
  "Bamboo Craft": "Wood, Bamboo & Cane",
  "Cane Craft": "Wood, Bamboo & Cane",
  "Wood Carving": "Wood, Bamboo & Cane",
  "Wooden Handicraft": "Wood, Bamboo & Cane",
  "Bamboo Basketry": "Basketry & Natural Fibres",
  "Cane Basketry": "Basketry & Natural Fibres",
  "Jute Craft": "Basketry & Natural Fibres",
  "Sabai Grass Craft": "Basketry & Natural Fibres",
  "Natural Fibre Craft": "Basketry & Natural Fibres",
  "Basket Making": "Basketry & Natural Fibres",
  "Marble Carving": "Stone & Sculpture",
  "Stone Carving": "Stone & Sculpture",
  "Konark-style Stone Craft": "Stone & Sculpture",
  "Mahabalipuram Sculpture": "Stone & Sculpture",
  "Traditional Sculpture": "Stone & Sculpture",
  "Channapatna Toys": "Toys & Dolls",
  "Bengal Dolls": "Toys & Dolls",
  "Kondapalli Toys": "Toys & Dolls",
  "Wooden Toys": "Toys & Dolls",
  "Clay Dolls": "Toys & Dolls",
  "Traditional Dolls": "Toys & Dolls",
  "Mojari": "Leather Craft",
  "Jutti": "Leather Craft",
  "Shantiniketan Leather": "Leather Craft",
  "Kolhapuri Footwear": "Leather Craft",
  "Traditional Leather Craft": "Leather Craft",
  "Kashmiri Papier-mâché": "Paper & Eco Crafts",
  "Handmade Paper Craft": "Paper & Eco Crafts",
  "Paper Décor": "Paper & Eco Crafts",
  "Eco Craft": "Paper & Eco Crafts",
  "Jute Eco Craft": "Paper & Eco Crafts",
  "Natural Fibre Eco Craft": "Paper & Eco Crafts",
  "Handwoven Home Textile": "Home & Living",
  "Terracotta Décor": "Home & Living",
  "Wooden Décor": "Home & Living",
  "Metal Décor": "Home & Living",
  "Cane Furniture": "Home & Living",
  "Handmade Basketry": "Home & Living",
  "Natural Fibre Décor": "Home & Living",
  "Traditional Home Textile": "Home & Living",
  "Kalamkari Painting": "Painting & Folk Art",
  "Dharmavaram Silk": "Handloom & Textiles",
  "Uppada Jamdani": "Handloom & Textiles",
  "Machilipatnam Block Print": "Handloom & Textiles",
  "Budithi Bell Metal Craft": "Metal & Dhokra",
  "Bobbili Veena Woodcraft": "Wood, Bamboo & Cane",
  "Venkatagiri Handloom": "Handloom & Textiles",
  "Leather Puppet Craft": "Leather Craft",
  "Durgi Stone Carving": "Stone & Sculpture",
  "Monpa Handmade Paper Craft": "Paper & Eco Crafts",
  "Sherdukpen Wood Carving": "Wood, Bamboo & Cane",
  "Apatani Handloom Weaving": "Handloom & Textiles",
  "Wancho Bead Jewellery": "Jewellery & Accessories",
  "Mishmi Handwoven Textile": "Handloom & Textiles",
  "Nyishi Cane & Bamboo Craft": "Wood, Bamboo & Cane",
  "Tangsa Tribal Weaving": "Handloom & Textiles",
  "Nocte Cane Basketry": "Basketry & Natural Fibres",
  "Khampti Wooden Mask Craft": "Wood, Bamboo & Cane",
  "Monpa Wool Weaving": "Handloom & Textiles",
  "Eri Silk": "Handloom & Textiles",
  "Handwoven Textile": "Handloom & Textiles",
  "Traditional Assamese Weaving": "Handloom & Textiles",
  "Bamboo Home Décor": "Home & Living",
  "Madhubani Painting": "Painting & Folk Art",
  "Bhagalpuri Tussar Silk": "Handloom & Textiles",
  "Sikki Grass Craft": "Basketry & Natural Fibres",
  "Sujani Embroidery": "Embroidery",
  "Tikuli Craft": "Painting & Folk Art",
  "Patna Wooden Toys": "Toys & Dolls",
  "Manjusha Painting": "Painting & Folk Art",
  "Bawan Buti Weaving": "Handloom & Textiles",
  "Wrought Iron Craft": "Metal & Dhokra",
  "Kosa Silk Weaving": "Handloom & Textiles",
  "Godna Painting": "Painting & Folk Art",
  "Bastar Wood Carving": "Wood, Bamboo & Cane",
  "Terracotta Craft": "Pottery & Clay",
  "Sisal Natural Fibre Craft": "Basketry & Natural Fibres",
  "Cowrie Shell Jewellery": "Jewellery & Accessories",
  "Tumba Gourd Craft": "Wood, Bamboo & Cane",
  "Goan Terracotta": "Pottery & Clay",
  "Cuncolim Wooden Craft": "Wood, Bamboo & Cane",
  "Coconut Shell Craft": "Wood, Bamboo & Cane",
  "Sea Shell Craft": "Jewellery & Accessories",
  "Brass Lamp Metal Craft": "Metal & Dhokra",
  "Traditional Crochet Lace": "Embroidery",
  "Jute Fibre Décor": "Home & Living",
  "Ceramic Tile Art": "Pottery & Clay",
  "Batik Textile Art": "Handloom & Textiles",
  "Rogan Painting": "Painting & Folk Art",
  "Patan Patola": "Handloom & Textiles",
  "Ajrakh Block Print": "Handloom & Textiles",
  "Tangaliya Weaving": "Handloom & Textiles",
  "Sankheda Lacquered Woodcraft": "Wood, Bamboo & Cane",
  "Copper Coated Bell Craft": "Metal & Dhokra",
  "Surat Zari Embroidery": "Embroidery",
  "Namda Wool Felt Craft": "Handloom & Textiles",
  "Phulkari Embroidery": "Embroidery",
  "Panipat Handloom Durries": "Handloom & Textiles",
  "Tila Mojari": "Leather Craft",
  "Jhajjar Pottery": "Pottery & Clay",
  "Terracotta Sculpture": "Pottery & Clay",
  "Khes Weaving": "Handloom & Textiles",
  "Brass Utensil Craft": "Metal & Dhokra",
  "Bone & Wood Inlay": "Wood, Bamboo & Cane",
  "Sarkanda Grass Craft": "Basketry & Natural Fibres",
  "Mudha Cane Furniture": "Wood, Bamboo & Cane",
  "Kullu Shawl Weaving": "Handloom & Textiles",
  "Chamba Rumal Embroidery": "Embroidery",
  "Kinnauri Handloom Weaving": "Handloom & Textiles",
  "Kangra Miniature Painting": "Painting & Folk Art",
  "Metal Bell & Temple Craft": "Metal & Dhokra",
  "Himachali Wood Carving": "Wood, Bamboo & Cane",
  "Lahauli Wool Knitted Craft": "Handloom & Textiles",
  "Mohra Metal Sculpture": "Metal & Dhokra",
  "Thangka Painting": "Painting & Folk Art",
  "Natural Grass Slippers Craft": "Basketry & Natural Fibres",
  "Sohrai Painting": "Painting & Folk Art",
  "Pyatkar Scroll Painting": "Painting & Folk Art",
  "Tribal Dhokra": "Metal & Dhokra",
  "Tussar Silk Handloom": "Handloom & Textiles",
  "Saraikela Chhau Masks": "Toys & Dolls",
  "Tribal Stone Carving": "Stone & Sculpture",
  "Tribal Wood Carving": "Wood, Bamboo & Cane",
  "Lac Bangle Craft": "Jewellery & Accessories",
  "Natural Fibre Weaving": "Basketry & Natural Fibres",
  "Mysore Rosewood Inlay": "Wood, Bamboo & Cane",
  "Bidriware": "Metal & Dhokra",
  "Ilkal Saree Weaving": "Handloom & Textiles",
  "Kinhal Wooden Toys": "Toys & Dolls",
  "Kasuti Embroidery": "Embroidery",
  "Guledgudda Khana Weaving": "Handloom & Textiles",
  "Udupi Handloom": "Handloom & Textiles",
  "Ganjifa Card Art": "Painting & Folk Art",
  "Navalgund Durrie Weaving": "Handloom & Textiles",
  "Aranmula Metal Mirror": "Metal & Dhokra",
  "Balaramapuram Handloom": "Handloom & Textiles",
  "Nettur Petti Woodcraft": "Wood, Bamboo & Cane",
  "Bell Metal Lamp Craft": "Metal & Dhokra",
  "Coir Craft": "Basketry & Natural Fibres",
  "Screwpine Mat Craft": "Basketry & Natural Fibres",
  "Kerala Mural Painting": "Painting & Folk Art",
  "Kannur Home Textiles": "Handloom & Textiles",
  "Bamboo Reeds Craft": "Wood, Bamboo & Cane",
  "Chanderi Weaving": "Handloom & Textiles",
  "Bagh Block Print": "Handloom & Textiles",
  "Maheshwari Handloom": "Handloom & Textiles",
  "Bell Metal Dhokra": "Metal & Dhokra",
  "Tikamgarh Brass Craft": "Metal & Dhokra",
  "Batik Textile Craft": "Handloom & Textiles",
  "Sandstone Screen Carving": "Stone & Sculpture",
  "Nandana Block Printing": "Handloom & Textiles",
  "Zardozi Velvet Embroidery": "Embroidery",
  "Paithani Silk Weaving": "Handloom & Textiles",
  "Solapur Chaddar Weaving": "Handloom & Textiles",
  "Sawantwadi Wooden Toys": "Toys & Dolls",
  "Hand-Beaten Copperware": "Metal & Dhokra",
  "Karvath Kati Tussar Weaving": "Handloom & Textiles",
  "Himroo Weaving": "Handloom & Textiles",
  "Mashru Textile Weaving": "Handloom & Textiles",
  "Bell Metal Utensil Craft": "Metal & Dhokra",
  "Kauna Reed Craft": "Basketry & Natural Fibres",
  "Longpi Black Pottery": "Pottery & Clay",
  "Shaphee Lanphee Embroidery": "Embroidery",
  "Wangkhei Phee Handloom": "Handloom & Textiles",
  "Moirang Phee Weaving": "Handloom & Textiles",
  "Cane & Bamboo Furniture": "Wood, Bamboo & Cane",
  "Kouna Reed Basketry": "Basketry & Natural Fibres",
  "Traditional Wood Carving": "Wood, Bamboo & Cane",
  "Traditional Potloi Dolls": "Toys & Dolls",
  "Bell Metal Craft": "Metal & Dhokra",
  "Khasi Cane Basketry": "Basketry & Natural Fibres",
  "Ryndia Eri Silk": "Handloom & Textiles",
  "Garo Dakmanda Weaving": "Handloom & Textiles",
  "Larnai Black Clay Pottery": "Pottery & Clay",
  "Endi Silk Spinning": "Handloom & Textiles",
  "Natural Reed Craft": "Basketry & Natural Fibres",
  "Garo Beaded Jewellery": "Jewellery & Accessories",
  "Cane Rain Shield Craft": "Basketry & Natural Fibres",
  "Puan Weaving": "Handloom & Textiles",
  "Mizo Bamboo Straw Hats": "Basketry & Natural Fibres",
  "Handloom Shawl Weaving": "Handloom & Textiles",
  "Bamboo Fish Basketry": "Basketry & Natural Fibres",
  "Traditional Beaded Headdress": "Jewellery & Accessories",
  "Banana Fibre Craft": "Basketry & Natural Fibres",
  "Naga Shawl Weaving": "Handloom & Textiles",
  "Konyak Wood Carving": "Wood, Bamboo & Cane",
  "Tribal Metal Forging": "Metal & Dhokra",
  "Angami Bamboo Basketry": "Basketry & Natural Fibres",
  "Traditional Beaded Jewellery": "Jewellery & Accessories",
  "Ao Striped Skirt Weaving": "Handloom & Textiles",
  "Lotha Handspun Weaving": "Handloom & Textiles",
  "Black Clay Pottery": "Pottery & Clay",
  "Natural Shell & Feather Craft": "Jewellery & Accessories",
  "Chakesang Backstrap Weaving": "Handloom & Textiles",
  "Pipili Appliqué": "Embroidery",
  "Odisha Dhokra": "Metal & Dhokra",
  "Cow Dung Toy Craft": "Toys & Dolls",
  "Golden Grass Craft": "Basketry & Natural Fibres",
  "Bomkai Handloom Weaving": "Handloom & Textiles",
  "Horn Craft": "Wood, Bamboo & Cane",
  "Hoshiarpur Wood Inlay": "Wood, Bamboo & Cane",
  "Traditional Durrie Weaving": "Handloom & Textiles",
  "Hand-Hammered Metal Craft": "Metal & Dhokra",
  "Parandi Tassel Craft": "Jewellery & Accessories",
  "Leather Sports Craft": "Leather Craft",
  "Molela Terracotta": "Pottery & Clay",
  "Bagru Block Print": "Handloom & Textiles",
  "Kota Doria": "Handloom & Textiles",
  "Sanganeri Block Print": "Handloom & Textiles",
  "Kundan & Meenakari Jewellery": "Jewellery & Accessories",
  "Pichwai Painting": "Painting & Folk Art",
  "Sheesham Wood Carving": "Wood, Bamboo & Cane",
  "Usta Art": "Leather Craft",
  "Choktse Wooden Tables": "Wood, Bamboo & Cane",
  "Lepcha Handloom Weaving": "Handloom & Textiles",
  "Tibetan Woollen Carpets": "Handloom & Textiles",
  "Cane & Bamboo Basketry": "Basketry & Natural Fibres",
  "Wooden Mask Carving": "Wood, Bamboo & Cane",
  "Woollen Blanket Weaving": "Handloom & Textiles",
  "Beaded Mala Craft": "Jewellery & Accessories",
  "Traditional Silver Metalwork": "Metal & Dhokra",
  "Thanjavur Gold Leaf Painting": "Painting & Folk Art",
  "Bronze Sculpture": "Stone & Sculpture",
  "Madurai Sungudi": "Handloom & Textiles",
  "Nachiarkoil Brass Lamps": "Metal & Dhokra",
  "Pattamadai Sedge Grass Mats": "Basketry & Natural Fibres",
  "Chettinad Athangudi Tiles": "Pottery & Clay",
  "Salem Handloom Weaving": "Handloom & Textiles",
  "Thanjavur Art Plates": "Metal & Dhokra",
  "Toda Embroidery": "Embroidery",
  "Pochampally Ikat": "Handloom & Textiles",
  "Gadwal Saree Weaving": "Handloom & Textiles",
  "Pembarthi Sheet Metal Craft": "Metal & Dhokra",
  "Nirmal Wooden Toys": "Toys & Dolls",
  "Cheriyal Scroll Painting": "Painting & Folk Art",
  "Siddipet Gollabhama Weaving": "Handloom & Textiles",
  "Adilabad Dhokra": "Metal & Dhokra",
  "Warangal Durrie Weaving": "Handloom & Textiles",
  "Telia Rumal Double Ikat": "Handloom & Textiles",
  "Risa Handwoven Breastcloth": "Handloom & Textiles",
  "Sitalpati Mat Craft": "Paper & Eco Crafts",
  "Eri Silk Weaving": "Handloom & Textiles",
  "Clay Terracotta Idols": "Pottery & Clay",
  "Tribal Bead Jewellery": "Jewellery & Accessories",
  "Bamboo Splint Craft": "Wood, Bamboo & Cane",
  "Handloom Pachra Weaving": "Handloom & Textiles",
  "Moradabad Brass Craft": "Metal & Dhokra",
  "Saharanpur Wood Carving": "Wood, Bamboo & Cane",
  "Bhadohi Woollen Carpets": "Handloom & Textiles",
  "Firozabad Glass Craft": "Home & Living",
  "Gorakhpur Terracotta": "Pottery & Clay",
  "Zardozi Embroidery": "Embroidery",
  "Mirzapur Durrie Weaving": "Handloom & Textiles",
  "Aipan Painting": "Painting & Folk Art",
  "Ringal Bamboo Basketry": "Basketry & Natural Fibres",
  "Thulma Woollen Weaving": "Handloom & Textiles",
  "Pankhi Woollen Shawls": "Handloom & Textiles",
  "Likhai Wood Carving": "Wood, Bamboo & Cane",
  "Copper Vessel Metal Craft": "Metal & Dhokra",
  "Nettle Natural Fibre Craft": "Basketry & Natural Fibres",
  "Pine Needle Craft": "Basketry & Natural Fibres",
  "Almora Tweed Weaving": "Handloom & Textiles",
  "Garhwal Wood Carving": "Wood, Bamboo & Cane",
  "Kantha Embroidery": "Embroidery",
  "Krishnanagar Clay Craft": "Pottery & Clay",
  "Shantiniketan Leather Craft": "Leather Craft",
  "Padauk Wood Carving": "Wood, Bamboo & Cane",
  "Polished Sea Shell Craft": "Jewellery & Accessories",
  "Mother of Pearl Jewellery": "Jewellery & Accessories",
  "Nicobarese Mat Weaving": "Basketry & Natural Fibres",
  "Soft Stone Carving": "Stone & Sculpture",
  "Marine Driftwood Décor": "Home & Living",
  "Palm Frond Basketry": "Basketry & Natural Fibres",
  "Coastal Natural Fibre Craft": "Basketry & Natural Fibres",
  "Studio Pottery": "Pottery & Clay",
  "Architectural Wood Carving": "Wood, Bamboo & Cane",
  "Macramé Fibre Craft": "Basketry & Natural Fibres",
  "Hand-Hammered Brassware": "Metal & Dhokra",
  "Recycled Glass Craft": "Home & Living",
  "Hand-Turned Woodcraft": "Wood, Bamboo & Cane",
  "Wild Reed Mat Weaving": "Basketry & Natural Fibres",
  "Traditional Inlay Craft": "Wood, Bamboo & Cane",
  "Coconut Frond Basketry": "Basketry & Natural Fibres",
  "Handwoven Fishnet Craft": "Handloom & Textiles",
  "Wooden Boat Model Craft": "Wood, Bamboo & Cane",
  "Terracotta Water Jugs": "Pottery & Clay",
  "Mughal Miniature Painting": "Painting & Folk Art",
  "Hand-Knotted Silk Carpets": "Handloom & Textiles",
  "Hand Block Printed Textile": "Handloom & Textiles",
  "Brass Metal Lamp Craft": "Metal & Dhokra",
  "Pashmina Weaving": "Handloom & Textiles",
  "Walnut Wood Carving": "Wood, Bamboo & Cane",
  "Kani Shawl Weaving": "Handloom & Textiles",
  "Tilla Embroidery": "Embroidery",
  "Sozni Embroidery": "Embroidery",
  "Copper Engraving": "Metal & Dhokra",
  "Khatamband Wood Inlay": "Wood, Bamboo & Cane",
  "Willow Wicker Basketry": "Basketry & Natural Fibres",
  "Pashmina Raw Wool Spinning": "Handloom & Textiles",
  "Woollen Rug Weaving": "Handloom & Textiles",
  "Ladakhi Metal Teapot Craft": "Metal & Dhokra",
  "Choktse Wood Carving": "Wood, Bamboo & Cane",
  "Pattu Wool Weaving": "Handloom & Textiles",
  "Clay Buddha Sculpting": "Pottery & Clay",
  "Natural Shrub Basketry": "Basketry & Natural Fibres",
  "Yak Wool Braid Craft": "Basketry & Natural Fibres",
  "Beaded Perak Headdress": "Jewellery & Accessories",
  "Coir Fibre Cordage": "Basketry & Natural Fibres",
  "Grass Mat Weaving": "Basketry & Natural Fibres",
  "Miniature Wooden Boat Craft": "Wood, Bamboo & Cane",
  "Coral Shell Jewellery": "Jewellery & Accessories",
  "Batik Island Textile": "Handloom & Textiles",
  "Coconut Wood Furniture": "Wood, Bamboo & Cane",
  "Palm Leaf Thatched Weaving": "Basketry & Natural Fibres",
  "Sea Glass Craft": "Home & Living",
  "Traditional Net Weaving": "Basketry & Natural Fibres",
  "Puducherry Terracotta": "Pottery & Clay",
  "Fine Needlework Embroidery": "Embroidery",
  "Hand-Rolled Incense Craft": "Home & Living",
  "Handcrafted Leather Craft": "Leather Craft",
  "Bronze Icon Casting": "Metal & Dhokra",
  "Studio Stoneware Pottery": "Pottery & Clay",
  "Cane & Rattan Furniture": "Wood, Bamboo & Cane",
  "Handloom Cotton Linen": "Handloom & Textiles",
  "Coconut Shell Jewellery": "Jewellery & Accessories"
});

export const categoryImageMap = Object.freeze({
  "Handloom & Textiles": "/demo_image/Handloom & Textiles.jpg",
  "Embroidery": "/demo_image/Embroidery.jpg",
  "Pottery & Clay": "/demo_image/pottery & clay.jpg",
  "Metal & Dhokra": "/demo_image/metal & dhokra.jpg",
  "Painting & Folk Art": "/demo_image/Painting & folk art.jpg",
  "Jewellery & Accessories": "/demo_image/Jewellery & Accessories.jpg",
  "Wood, Bamboo & Cane": "/demo_image/wood bamboo and cane.jpg",
  "Basketry & Natural Fibres": "/demo_image/basketry and natural fibres.jpg",
  "Stone & Sculpture": "/demo_image/stone and sculpture.jpg",
  "Toys & Dolls": "/demo_image/toys and dolls.jpg",
  "Leather Craft": "/demo_image/leather craft.jpg",
  "Paper & Eco Crafts": "/demo_image/paper and eco crafts.jpg",
  "Home & Living": "/demo_image/home and living.jpg"
});

export const DEFAULT_CRAFT_IMAGE = '/demo_image/default.jpg';

/**
 * Returns the parent category name for a given craftType
 * @param {string} craftType 
 * @returns {string} Category name
 */
export function getCraftCategory(craftType) {
  if (!craftType) return 'Handloom & Textiles';
  return craftCategoryMap[craftType] || 'Handloom & Textiles';
}

/**
 * Returns the exact verified image URL for a given craftType by resolving
 * through its parent category.
 * @param {string} craftType 
 * @returns {string} Image path (e.g. '/demo_image/Handloom & Textiles.jpg')
 */
export function getCraftImage(craftType) {
  const category = craftCategoryMap[craftType];
  if (!category) {
    console.warn(`Unknown craftType: ${craftType}`);
    return DEFAULT_CRAFT_IMAGE;
  }
  return categoryImageMap[category] || DEFAULT_CRAFT_IMAGE;
}
