import { API_BASE_URL } from '../utils/api';
import {productMediaUrl} from '../utils/productApi.js';
import React,{useEffect,useRef,useState} from 'react';
import {useAuth} from '../context/AuthContext';
export default function ProductReviews({productId,onChanged}){
 const {user,token}=useAuth();const [reviews,setReviews]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[editing,setEditing]=useState(false),[rating,setRating]=useState(5),[text,setText]=useState(''),[saving,setSaving]=useState(false);const busy=useRef(false);
 useEffect(()=>{const controller=new AbortController();fetch(`${API_BASE_URL}/api/catalog/products/${productId}/reviews`,{signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('Could not load reviews.');return r.json();}).then(d=>setReviews(d.reviews)).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>setLoading(false));return()=>controller.abort();},[productId]);
 const own=reviews.find(r=>r.patron.id===user?.id);const average=reviews.length?reviews.reduce((sum,r)=>sum+r.rating,0)/reviews.length:null;
 async function submit(event){event.preventDefault();if(busy.current)return;busy.current=true;setSaving(true);setError('');try{const r=await fetch(`${API_BASE_URL}/api/catalog/products/${productId}/reviews${own?'/'+own.id:''}`,{method:own?'PATCH':'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({rating,text})});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not save review.');setReviews(rows=>[d.review,...rows.filter(row=>row.id!==d.review.id)]);setEditing(false);onChanged();}catch(e){setError(e.message);}finally{busy.current=false;setSaving(false);}}
 return <div className="bg-surface-container-lowest rounded-2xl p-6 sm:p-8 border border-outline-variant space-y-4"><h3 className="text-2xl font-garamond">Patron reviews</h3>{loading?<p>Loading reviews...</p>:<p aria-label="Average rating">{'\u2605'.repeat(Math.round(average||0))}{'\u2606'.repeat(5-Math.round(average||0))} | {average===null?'Not rated':`${average.toFixed(1)} / 5`} | Based on {reviews.length} reviews</p>}{error&&<p role="alert">{error}</p>}{user?.role==='PATRON'&&!editing&&<button className="heritage-button" onClick={()=>{setRating(own?.rating||5);setText(own?.text||'');setEditing(true);}}>{own?'Edit Your Review':'Write a Review'}</button>}{editing&&<form onSubmit={submit} className="space-y-3"><fieldset><legend>Your rating</legend>{[1,2,3,4,5].map(n=><label key={n} className="mr-3"><input type="radio" name="rating" value={n} checked={rating===n} onChange={()=>setRating(n)}/>{n} &#9733;</label>)}</fieldset><label className="block">Your review<textarea required maxLength={3000} value={text} onChange={e=>setText(e.target.value)} className="block w-full p-3 bg-surface border border-outline-variant rounded-lg"/></label><button disabled={saving} className="heritage-button">{saving?'Saving...':'Submit review'}</button><button type="button" disabled={saving} onClick={()=>setEditing(false)} className="ml-4">Cancel</button></form>}{reviews.map(r=><article key={r.id} className="bg-surface p-5 border border-outline-variant rounded-xl"><div className="flex gap-3 items-center"><img src={productMediaUrl(r.patron.avatarUrl)||'/images/demo/customer male.png'} alt="" className="w-12 h-12 rounded-full object-cover"/><div><strong>{r.patron.name}</strong><p>{'\u2605'.repeat(r.rating)}{'\u2606'.repeat(5-r.rating)} | {new Date(r.createdAt).toLocaleDateString()}</p></div></div><p className="mt-3 whitespace-pre-wrap">{r.text}</p></article>)}</div>;
}
