import React,{useEffect,useRef,useState} from 'react';
import {getSellerProduct,updateSellerProduct,archiveSellerProduct,productMediaUrl} from '../utils/productApi.js';
import {CRAFT_CATEGORIES} from '../constants/craftCategories.js';
import {normalizeSellerProduct} from '../utils/sellerProducts.js';
import {formatEvidenceScore} from '../utils/evidenceFormat.js';
import ProductGallery from './ProductGallery';
const fields=[['title','Title'],['price','Price','number'],['stock','Stock','number'],['region','Region'],['dimensions','Dimensions'],['craft_technique','Craft technique'],['giTag','GI / certification information']];
export default function SellerProductAction({id,mode,token,onClose,onSaved,onSignIn}){
 const [product,setProduct]=useState(null),[form,setForm]=useState(null),[error,setError]=useState(''),[expired,setExpired]=useState(false),[saving,setSaving]=useState(false);const busy=useRef(false),dialog=useRef(null);
 useEffect(()=>{dialog.current?.focus();let active=true;getSellerProduct(id,token).then(({product:p})=>{if(!active)return;const normalized=normalizeSellerProduct(p);setProduct(normalized);setForm({...normalized,materials:normalized.materials.join(', ')});}).catch(e=>{if(active){setError(e.message);setExpired(e.status===401);}});return()=>{active=false;};},[id,token]);
 async function submit(event){event.preventDefault();if(busy.current)return;busy.current=true;setSaving(true);setError('');try{
  if(mode==='delete')await archiveSellerProduct(id,token);else{
   const patch=Object.fromEntries([...fields.map(([key])=>[key,form[key]??'']),['category',form.category],['description',form.description],['materials',form.materials.split(',').map(s=>s.trim()).filter(Boolean)]]);
   patch.price=Number(patch.price);patch.stock=Number(patch.stock);await updateSellerProduct(id,patch,token);
  }onSaved();onClose();
 }catch(e){setError(e.message||'Could not save this change. Please try again.');setExpired(e.status===401);}finally{busy.current=false;setSaving(false);}}
 const input='block w-full rounded-lg border border-seller-border bg-seller-card p-2 mt-1';
 const close=()=>{if(!busy.current)onClose();};
 return <div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center p-4" onKeyDown={e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const controls=[...dialog.current.querySelectorAll('button:not(:disabled),input,select,textarea')];const first=controls[0],last=controls.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialog.current)){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}><section ref={dialog} tabIndex={-1} role="dialog" aria-modal="true" aria-label={mode==='delete'?'Delete this product?':mode==='edit'?'Edit product':'View product'} className="bg-seller-card text-seller-text border border-seller-border rounded-2xl p-6 max-w-3xl w-full max-h-[90vh] overflow-y-auto space-y-4"><button disabled={saving} onClick={close} className="underline">Back to My Products</button><h2 className="text-xl font-bold">{mode==='delete'?'Delete this product?':mode==='edit'?'Edit product':product?.title||'View product'}</h2>{error&&<p role="alert">{error} {expired&&<button onClick={onSignIn} className="underline">Sign in again</button>}</p>}{!product&&!error&&<p role="status">Loading product...</p>}
 {product&&mode==='view'&&<><ProductGallery product={{...product,images:[product.image,...(product.media?.images||[]).filter((_,i)=>i!==(product.media.primaryImageIndex||0)).map(productMediaUrl)].filter(Boolean),media:{...product.media,productVideo:productMediaUrl(product.media?.productVideo),processVideo:productMediaUrl(product.media?.processVideo)}}}/><dl className="grid grid-cols-2 gap-3">{[...fields,['category','Category'],['materials','Materials'],['description','Description']].map(([key,label])=><div key={key}><dt className="font-semibold">{label}</dt><dd>{Array.isArray(product[key])?product[key].join(', '):String(product[key]??'Not provided')}</dd></div>)}</dl><p>KARIGAR Trust Evidence Score: {formatEvidenceScore(product.evidence.score)} / 100</p>{Object.entries(product.evidence.categories||{}).map(([key,value])=><p key={key}>{key.replaceAll('_',' ')}: {formatEvidenceScore(value.score)} / {value.max_score}</p>)}<p className="text-xs">This score reflects supporting and transparency evidence for the listing. It is not an authenticity guarantee.</p></>}
 {product&&mode!=='view'&&<form onSubmit={submit} className="space-y-4">{mode==='delete'?<p>Delete <strong>{product.title}</strong>? This listing will disappear from the buyer marketplace. Historical orders and reviews will be retained.</p>:<><p className="text-sm">Editing listing details preserves existing media and the stored evidence snapshot; it does not rerun analysis.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{fields.map(([key,label,type='text'])=><label key={key}>{label}<input required={['title','price','stock'].includes(key)} type={type} min={key==='price'?'0.01':type==='number'?0:undefined} step={key==='price'?'any':1} className={input} value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>Category<select className={input} value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{CRAFT_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><label>Materials (comma separated)<input className={input} value={form.materials} onChange={e=>setForm({...form,materials:e.target.value})}/></label><label>Description<textarea className={input} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div></>}<div className="flex gap-4"><button type="button" disabled={saving} onClick={close}>Cancel</button><button disabled={saving||expired} className="bg-seller-accent rounded-lg px-4 py-2">{saving?'Saving...':mode==='delete'?'Delete Product':'Save changes'}</button></div></form>}</section></div>;
}
