const fs = require('fs');
const path = require('path');

const additions = {
  en: {
    footer: {
      compactDesc: "Karigar Direct Artisan Marketplace © 2026. Empowering Indian Craftsmanship.",
      compactEscrow: "Escrow Protected Direct Trade",
      compactSupport: "Artisan Support: 1800-KARIGAR"
    },
    orderDetails: {
      indiaPostCarrier: "India Post Artisan Express"
    },
    messages: {
      messageSentSuccess: "Message sent to buyer",
      searchPlaceholder: "Search conversations...",
      re: "Re:",
      escrowVerified: "Escrow Order Verified",
      endToEndSecurity: "End-to-End Escrow Protected Direct Communication",
      translatedLabel: "Auto Translated:"
    },
    settings: {
      artisanProfile: "Artisan Profile",
      aadhaarGiVerified: "Aadhaar & GI Verified",
      fullName: "Full Name",
      craftSpecialization: "Craft Specialization",
      phoneForSms: "Phone Number (For Order SMS)",
      workshopAddress: "Workshop / Kiln Physical Address",
      directPayoutTitle: "Direct Payout Bank Account",
      aadhaarSeededDesc: "Bank account is Aadhaar-seeded for direct escrow disbursements from verified buyer payments.",
      accountHolderName: "Account Holder Name",
      bankName: "Bank Name",
      accountNumber: "Account Number",
      ifscCode: "IFSC Code",
      alertsAndNotifications: "Alerts & Notifications",
      smsAlertsTitle: "Instant SMS Dispatch Alerts",
      smsAlertsDesc: "Receive SMS alerts when a new order is confirmed.",
      whatsappAudioTitle: "WhatsApp Audio Updates",
      whatsappAudioDesc: "Get payout notifications and voice notes via WhatsApp.",
      langChangedToast: "Language changed to {{lang}}"
    },
    profile: {
      trustScore: "Trust Score",
      kycVerifiedBadge: "100% KYC Verified",
      aboutArtisanLabel: "About Artisan:",
      myOrdersTitle: "My Orders",
      myOrdersSubtitle: "Recent customer orders and shipments fulfilled by your studio.",
      viewAll: "View All",
      thProduct: "Product",
      thAmount: "Amount",
      thStatus: "Status",
      thDate: "Date",
      tabFallbackTitle: "{{tab}} Management",
      tabFallbackDesc: "Your {{tab}} are encrypted and linked with your verified Karigar artisan credentials.",
      backToOverview: "← Back to Profile Overview",
      editProfileModalTitle: "Edit Artisan Profile",
      editProfileModalSubtitle: "Update your personal, craft, and cluster details stored in localStorage.",
      changePhoto: "Change Profile Photo",
      fullNameReq: "Full Name",
      phoneReq: "Phone",
      emailReq: "Email",
      craftTypeReq: "Craft Type",
      stateLabel: "State",
      districtLabel: "District",
      experienceLabel: "Years of Experience",
      businessNameLabel: "Business / Artisan Name",
      aboutArtisanField: "About Artisan",
      saveProfileSuccess: "Profile updated and saved to localStorage successfully.",
      saveProfileError: "Failed to save profile changes.",
      cancel: "Cancel",
      saveChanges: "Save Changes"
    },
    addProduct: {
      step1Title: "Step 1 — Upload Product Images",
      step1Subtitle: "Take photos on your phone or upload high-resolution craft images. Karigar AI enhances lighting and verifies authenticity automatically.",
      dragDropTitle: "Drag & drop product images",
      orText: "or",
      clickToBrowse: "click to browse files",
      fromDevice: "from your computer or camera",
      uploadFormats: "Supports JPEG, PNG, WEBP • Multiple images allowed (up to 5 photos)",
      sampleCraftsTitle: "Or choose sample authentic craft images to test:",
      verifiedCraftsBadge: "Verified Indian Crafts",
      giRegisteredBadge: "GI Registered",
      selectedImagesTitle: "Selected Product Images:",
      primaryBadge: "Primary",
      step2Title: "Step 2 — Product Details",
      step2Subtitle: "Enter your craft details or speak naturally using your microphone.",
      productNameLabel: "Product Name *",
      productNamePlaceholder: "e.g. Handcrafted Bengal Terracotta Decorative Pot",
      categoryLabel: "Category *",
      catPottery: "Pottery & Ceramics",
      catBamboo: "Bamboo & Cane Craft",
      catWood: "Woodcraft & Carvings",
      catPainting: "Folk Painting & Art",
      catMetal: "Dhokra & Brass Metalwork",
      catHandloom: "Handloom & Textiles",
      priceLabel: "Price (₹) *",
      pricePlaceholder: "1099",
      materialLabel: "Material Used *",
      materialPlaceholder: "e.g. Alluvial Terracotta Clay",
      stateRegionLabel: "State / Region *",
      stateRegionPlaceholder: "e.g. West Bengal",
      craftTypeLabel: "Craft Type *",
      craftTypePlaceholder: "e.g. Bankura Panchmura Pottery",
      giTagLabel: "GI Tag Verification",
      govtCertified: "Government Certified",
      giNone: "None / Other Traditional Craft",
      stockLabel: "Stock Quantity *",
      stockPlaceholder: "15",
      descLabel: "Product Description *",
      descPlaceholder: "Describe your craft, inspiration, firing methods, dimensions...",
      backToImages: "Back to Images",
      proceedToAI: "Generate with AI",
      aiStudioTitle: "Karigar AI Catalog & Authenticity Studio",
      aiStudioSubtitle: "Enhancing physical craft images, estimating fair artisan prices & evaluating authenticity signals.",
      allStepsComplete: "All 9 Processing Steps Complete",
      aiProcessingMetadata: "AI Processing Craft Metadata...",
      processingComplete: "Processing Complete",
      aiStepBackground: "Removing background",
      aiStepEnhance: "Enhancing image",
      aiStepLighting: "Improving lighting",
      aiStepAuthenticity: "Checking image authenticity",
      aiStepTitle: "Generating product title",
      aiStepDescription: "Generating description",
      aiStepTranslating: "Translating content",
      aiStepMarketPrice: "Analysing market price",
      aiStepSuggestedPrice: "Generating suggested price",
      catalogPreviewTitle: "AI Generated Catalog Preview",
      regenerate: "Regenerate",
      edit: "Edit",
      aiGenTitleLabel: "AI Generated Title:",
      aiGenDescLabel: "AI Generated Description:",
      suggestedCategory: "Suggested Category:",
      material: "Material:",
      origin: "Origin:",
      marketPriceAnalysis: "Market Price Range Analysis:",
      suggestedPriceLabel: "Suggested Price:",
      recommendedPriceLabel: "Recommended Listing Price:",
      acceptAISuggestions: "Accept AI Suggestions & Review",
      authenticityCheckTitle: "Product Authenticity Check",
      screenedBadge: "Screened",
      authenticityConfidence: "Authenticity Confidence",
      statusLikelyAuthentic: "Status: Likely Authentic ✓",
      sigAiImage: "AI Image Detection",
      sigAiImagePassed: "Passed (Natural)",
      sigDuplicate: "Duplicate Image Check",
      sigDuplicateMatches: "0 Matches (Original)",
      sigManipulation: "Image Manipulation Check",
      sigManipulationClean: "Clean (No Edits)",
      sigConsistency: "Image/Product Consistency",
      sigConsistencyMatch: "94% Match",
      authenticityNote: "“Multiple signals are used to estimate image authenticity. AI detection estimates probability based on sensor patterns and physical light scattering.”",
      step4Title: "Step 4 — Review & Publish",
      step4Subtitle: "Inspect your final marketplace listing, verified credentials, and escrow protection details.",
      readyForGlobalBuyers: "Ready for Global Buyers",
      aiEnhancedLighting: "AI Enhanced & Lighting Normalized",
      artisanPrefix: "Artisan:",
      trustScoreValue: "Trust Score: 4.8 / 5",
      unitsReadyWorkshop: "units ready in workshop",
      craftStoryDetails: "Craft Story & Details:",
      includedBadges: "Included Verification Badges:",
      badgeIdentity: "Identity Verified",
      badgeGI: "GI Verified (GI-452)",
      badgeImage: "Authentic Image (92%)",
      badgeCluster: "Cluster Verified",
      badgeProcess: "Process Proof",
      backToAI: "Back to AI Suggestions",
      saveAsDraft: "Save as Draft",
      publishProduct: "Publish Product"
    }
  },
  hi: {
    footer: {
      compactDesc: "कारीगर प्रत्यक्ष शिल्पी बाज़ार © 2026। भारतीय शिल्प कौशल का सशक्तिकरण।",
      compactEscrow: "एस्क्रो सुरक्षित प्रत्यक्ष व्यापार",
      compactSupport: "कारीगर सहायता: 1800-KARIGAR"
    },
    orderDetails: {
      indiaPostCarrier: "भारतीय डाक कारीगर एक्सप्रेस"
    },
    messages: {
      messageSentSuccess: "खरीदार को संदेश भेजा गया",
      searchPlaceholder: "बातचीत खोजें...",
      re: "संदर्भ:",
      escrowVerified: "एस्क्रो ऑर्डर सत्यापित",
      endToEndSecurity: "शुरुआत से अंत तक एस्क्रो सुरक्षित सीधा संवाद",
      translatedLabel: "स्वतः अनुवादित:"
    },
    settings: {
      artisanProfile: "कारीगर प्रोफ़ाइल",
      aadhaarGiVerified: "आधार एवं जीआई सत्यापित",
      fullName: "पूरा नाम",
      craftSpecialization: "शिल्प विशेषता",
      phoneForSms: "फ़ोन नंबर (ऑर्डर एसएमएस के लिए)",
      workshopAddress: "कार्यशाला / भट्टी का भौतिक पता",
      directPayoutTitle: "प्रत्यक्ष भुगतान बैंक खाता",
      aadhaarSeededDesc: "सत्यापित खरीदार भुगतान से प्रत्यक्ष एस्क्रो संवितरण के लिए बैंक खाता आधार-लिंक्ड है।",
      accountHolderName: "खाताधारक का नाम",
      bankName: "बैंक का नाम",
      accountNumber: "खाता संख्या",
      ifscCode: "आईएफएससी कोड",
      alertsAndNotifications: "अलर्ट और सूचनाएं",
      smsAlertsTitle: "त्वरित एसएमएस प्रेषण अलर्ट",
      smsAlertsDesc: "नया ऑर्डर पक्का होने पर तत्काल एसएमएस अलर्ट प्राप्त करें।",
      whatsappAudioTitle: "व्हाट्सएप ऑडियो अपडेट",
      whatsappAudioDesc: "व्हाट्सएप के माध्यम से भुगतान सूचनाएं और ध्वनि संदेश प्राप्त करें।",
      langChangedToast: "भाषा बदलकर {{lang}} कर दी गई"
    },
    profile: {
      trustScore: "विश्वास स्कोर",
      kycVerifiedBadge: "100% केवाईसी सत्यापित",
      aboutArtisanLabel: "कारीगर के बारे में:",
      myOrdersTitle: "मेरे ऑर्डर",
      myOrdersSubtitle: "आपकी कार्यशाला द्वारा पूरे किए गए हालिया ग्राहक ऑर्डर और शिपमेंट।",
      viewAll: "सभी देखें",
      thProduct: "उत्पाद",
      thAmount: "राशि",
      thStatus: "स्थिति",
      thDate: "दिनांक",
      tabFallbackTitle: "{{tab}} प्रबंधन",
      tabFallbackDesc: "आपकी {{tab}} सुरक्षित रूप से एन्क्रिप्टेड है और आपके सत्यापित कारीगर प्रमाण पत्र से जुड़ी है।",
      backToOverview: "← प्रोफ़ाइल विवरण पर वापस जाएं",
      editProfileModalTitle: "कारीगर प्रोफ़ाइल संपादित करें",
      editProfileModalSubtitle: "लोकल स्टोरेज में सहेजे गए अपने व्यक्तिगत, शिल्प और क्लस्टर विवरण को अपडेट करें।",
      changePhoto: "प्रोफ़ाइल फ़ोटो बदलें",
      fullNameReq: "पूरा नाम",
      phoneReq: "फ़ोन",
      emailReq: "ईमेल",
      craftTypeReq: "शिल्प प्रकार",
      stateLabel: "राज्य",
      districtLabel: "ज़िला",
      experienceLabel: "अनुभव के वर्ष",
      businessNameLabel: "व्यवसाय / कारीगर का नाम",
      aboutArtisanField: "कारीगर के बारे में",
      saveProfileSuccess: "प्रोफ़ाइल सफलतापूर्वक अपडेट और लोकल स्टोरेज में सुरक्षित की गई।",
      saveProfileError: "प्रोफ़ाइल परिवर्तनों को सहेजने में विफल।",
      cancel: "रद्द करें",
      saveChanges: "परिवर्तन सहेजें"
    },
    addProduct: {
      step1Title: "चरण 1 — उत्पाद छवियां अपलोड करें",
      step1Subtitle: "अपने फ़ोन से फ़ोटो लें या उच्च-रिज़ॉल्यूशन शिल्प छवियां अपलोड करें। कारीगर एआई रोशनी सुधारता है और प्रामाणिकता की स्वतः जांच करता है।",
      dragDropTitle: "उत्पाद छवियां खींचें और छोड़ें",
      orText: "या",
      clickToBrowse: "फ़ाइलें ब्राउज़ करने के लिए क्लिक करें",
      fromDevice: "अपने कंप्यूटर या कैमरे से",
      uploadFormats: "JPEG, PNG, WEBP समर्थित • अधिकतम 5 तस्वीरें अपलोड करें",
      sampleCraftsTitle: "या परीक्षण हेतु प्रामाणिक शिल्प छवियां चुनें:",
      verifiedCraftsBadge: "सत्यापित भारतीय शिल्प",
      giRegisteredBadge: "जीआई पंजीकृत",
      selectedImagesTitle: "चयनित उत्पाद छवियां:",
      primaryBadge: "मुख्य",
      step2Title: "चरण 2 — उत्पाद विवरण",
      step2Subtitle: "अपने शिल्प विवरण दर्ज करें या माइक्रोफ़ोन का उपयोग करके स्वाभाविक रूप से बोलें।",
      productNameLabel: "उत्पाद का नाम *",
      productNamePlaceholder: "उदा. हस्तनिर्मित बंगाल टेराकोटा सजावटी घड़ा",
      categoryLabel: "श्रेणी *",
      catPottery: "मिट्टी के बर्तन और चीनी मिट्टी",
      catBamboo: "बांस और बेंत शिल्प",
      catWood: "काष्ठकला और नक्काशी",
      catPainting: "लोक चित्रकला और कला",
      catMetal: "ढोकरा और पीतल धातुशिल्प",
      catHandloom: "हथकरघा और वस्त्र",
      priceLabel: "मूल्य (₹) *",
      pricePlaceholder: "1099",
      materialLabel: "प्रयुक्त सामग्री *",
      materialPlaceholder: "उदा. जलोढ़ टेराकोटा मिट्टी",
      stateRegionLabel: "राज्य / क्षेत्र *",
      stateRegionPlaceholder: "उदा. पश्चिम बंगाल",
      craftTypeLabel: "शिल्प प्रकार *",
      craftTypePlaceholder: "उदा. बांकुड़ा पंचमुरा मिट्टी के बर्तन",
      giTagLabel: "जीआई टैग सत्यापन",
      govtCertified: "सरकारी प्रमाणित",
      giNone: "कोई नहीं / अन्य पारंपरिक शिल्प",
      stockLabel: "स्टॉक मात्रा *",
      stockPlaceholder: "15",
      descLabel: "उत्पाद विवरण *",
      descPlaceholder: "अपने शिल्प, प्रेरणा, पकाने की विधि, माप आदि का वर्णन करें...",
      backToImages: "छवियों पर वापस जाएं",
      proceedToAI: "एआई द्वारा तैयार करें",
      aiStudioTitle: "कारीगर एआई कैटलॉग एवं प्रामाणिकता स्टूडियो",
      aiStudioSubtitle: "शिल्प छवियों को संवारना, उचित मूल्य निर्धारण और प्रामाणिकता संकेतों का मूल्यांकन।",
      allStepsComplete: "सभी 9 प्रसंस्करण चरण पूर्ण",
      aiProcessingMetadata: "एआई शिल्प विवरण का विश्लेषण कर रहा है...",
      processingComplete: "प्रसंस्करण पूर्ण हुआ",
      aiStepBackground: "पृष्ठभूमि हटाना",
      aiStepEnhance: "छवि की गुणवत्ता बढ़ाना",
      aiStepLighting: "प्रकाश व्यवस्था में सुधार",
      aiStepAuthenticity: "छवि प्रामाणिकता की जांच",
      aiStepTitle: "उत्पाद शीर्षक तैयार करना",
      aiStepDescription: "विवरण तैयार करना",
      aiStepTranslating: "सामग्री का अनुवाद",
      aiStepMarketPrice: "बाजार मूल्य का विश्लेषण",
      aiStepSuggestedPrice: "सुझाया गया मूल्य तैयार करना",
      catalogPreviewTitle: "एआई जनित कैटलॉग पूर्वावलोकन",
      regenerate: "पुनः उत्पन्न करें",
      edit: "संपादित करें",
      aiGenTitleLabel: "एआई जनित शीर्षक:",
      aiGenDescLabel: "एआई जनित विवरण:",
      suggestedCategory: "सुझाई गई श्रेणी:",
      material: "सामग्री:",
      origin: "उत्पत्ति:",
      marketPriceAnalysis: "बाजार मूल्य सीमा विश्लेषण:",
      suggestedPriceLabel: "सुझाया गया मूल्य:",
      recommendedPriceLabel: "अनुशंसित सूची मूल्य:",
      acceptAISuggestions: "एआई सुझाव स्वीकारें और समीक्षा करें",
      authenticityCheckTitle: "उत्पाद प्रामाणिकता जांच",
      screenedBadge: "सत्यापित",
      authenticityConfidence: "प्रामाणिकता विश्वास स्तर",
      statusLikelyAuthentic: "स्थिति: संभवतः प्रामाणिक ✓",
      sigAiImage: "एआई छवि पहचान",
      sigAiImagePassed: "सफल (प्राकृतिक)",
      sigDuplicate: "समान प्रतिरूप जांच",
      sigDuplicateMatches: "0 समानता (मूल कृति)",
      sigManipulation: "छवि संपादन जांच",
      sigManipulationClean: "स्वच्छ (कोई संपादन नहीं)",
      sigConsistency: "छवि/उत्पाद संगति",
      sigConsistencyMatch: "94% मेल",
      authenticityNote: "“छवि प्रामाणिकता का आकलन करने के लिए कई संकेतों का उपयोग किया जाता है। एआई पहचान सेंसर पैटर्न और प्रकाश प्रकीर्णन पर आधारित है।”",
      step4Title: "चरण 4 — समीक्षा और प्रकाशित करें",
      step4Subtitle: "अपनी अंतिम बाज़ार सूची, सत्यापित साख और एस्क्रो सुरक्षा विवरण की समीक्षा करें।",
      readyForGlobalBuyers: "वैश्विक खरीदारों के लिए तैयार",
      aiEnhancedLighting: "एआई परिष्कृत एवं संतुलित प्रकाश",
      artisanPrefix: "कारीगर:",
      trustScoreValue: "विश्वास स्कोर: 4.8 / 5",
      unitsReadyWorkshop: "इकाइयां कार्यशाला में तैयार",
      craftStoryDetails: "शिल्प कथा और विवरण:",
      includedBadges: "शामिल सत्यापन बैज:",
      badgeIdentity: "पहचान सत्यापित",
      badgeGI: "जीआई सत्यापित (GI-452)",
      badgeImage: "प्रामाणिक छवि (92%)",
      badgeCluster: "क्लस्टर सत्यापित",
      badgeProcess: "प्रक्रिया प्रमाण",
      backToAI: "एआई सुझावों पर वापस जाएं",
      saveAsDraft: "ड्राफ्ट के रूप में सहेजें",
      publishProduct: "उत्पाद प्रकाशित करें"
    }
  },
  bn: {
    footer: {
      compactDesc: "কারিগর সরাসরি কারুশিল্প বাজার © ২০২৬। ভারতীয় কারুশিল্পের ক্ষমতায়ন।",
      compactEscrow: "এসক্রো সুরক্ষিত সরাসরি বাণিজ্য",
      compactSupport: "কারিগর সহায়তা: 1800-KARIGAR"
    },
    orderDetails: {
      indiaPostCarrier: "ভারতীয় ডাক কারিগর এক্সপ্রেস"
    },
    messages: {
      messageSentSuccess: "ক্রেতাকে বার্তা পাঠানো হয়েছে",
      searchPlaceholder: "কথোপকথন অনুসন্ধান করুন...",
      re: "বিষয়:",
      escrowVerified: "এসক্রো অর্ডার যাচাইকৃত",
      endToEndSecurity: "শুরু থেকে শেষ পর্যন্ত এসক্রো সুরক্ষিত সরাসরি যোগাযোগ",
      translatedLabel: "স্বয়ংক্রিয় অনুবাদ:"
    },
    settings: {
      artisanProfile: "কারিগর প্রোফাইল",
      aadhaarGiVerified: "আধার ও জিআই যাচাইকৃত",
      fullName: "সম্পূর্ণ নাম",
      craftSpecialization: "কারুশিল্পের দক্ষতা",
      phoneForSms: "ফোন নম্বর (অর্ডার এসএমএস-এর জন্য)",
      workshopAddress: "কর্মশালা / ভাটার ঠিকানা",
      directPayoutTitle: "সরাসরি অর্থপ্রদানের ব্যাংক একাউন্ট",
      aadhaarSeededDesc: "যাচাইকৃত ক্রেতার অর্থ সরাসরি এসক্রো স্থানান্তরের জন্য ব্যাংক একাউন্টটি আধার সংযুক্ত।",
      accountHolderName: "হিসাবধারীর নাম",
      bankName: "ব্যাংকের নাম",
      accountNumber: "হিসাব নম্বর",
      ifscCode: "আইএফএসসি কোড",
      alertsAndNotifications: "সতর্কতা ও বিজ্ঞপ্তি",
      smsAlertsTitle: "তাত্ক্ষণিক এসএমএস প্রেরণের সতর্কতা",
      smsAlertsDesc: "নতুন অর্ডার নিশ্চিত হলে সঙ্গে সঙ্গে এসএমএস বার্তা পান।",
      whatsappAudioTitle: "হোয়াটসঅ্যাপ অডিও আপডেট",
      whatsappAudioDesc: "হোয়াটসঅ্যাপের মাধ্যমে পেমেন্ট বিজ্ঞপ্তি ও ভয়েস নোট পান।",
      langChangedToast: "ভাষা পরিবর্তন করে {{lang}} করা হয়েছে"
    },
    profile: {
      trustScore: "বিশ্বাস স্কোর",
      kycVerifiedBadge: "১০০% কেওয়াইসি যাচাইকৃত",
      aboutArtisanLabel: "কারিগর সম্পর্কে:",
      myOrdersTitle: "আমার অর্ডারসমূহ",
      myOrdersSubtitle: "আপনার স্টুডিও দ্বারা সরবরাহকৃত সাম্প্রতিক গ্রাহক অর্ডার ও চালান।",
      viewAll: "সব দেখুন",
      thProduct: "পণ্য",
      thAmount: "পরিমাণ",
      thStatus: "স্থিতি",
      thDate: "তারিখ",
      tabFallbackTitle: "{{tab}} পরিচালনা",
      tabFallbackDesc: "আপনার {{tab}} সুরক্ষিতভাবে এনক্রিপ্ট করা এবং আপনার যাচাইকৃত কারিগর প্রশংসাপত্রের সাথে সংযুক্ত।",
      backToOverview: "← প্রোফাইল সারসংক্ষেপে ফিরে যান",
      editProfileModalTitle: "কারিগর প্রোফাইল সম্পাদনা",
      editProfileModalSubtitle: "লোকাল স্টোরেজে সংরক্ষিত আপনার ব্যক্তিগত, কারুশিল্প ও ক্লাস্টার বিবরণ আপডেট করুন।",
      changePhoto: "প্রোফাইল ছবি পরিবর্তন করুন",
      fullNameReq: "সম্পূর্ণ নাম",
      phoneReq: "ফোন",
      emailReq: "ইমেল",
      craftTypeReq: "কারুশিল্পের ধরন",
      stateLabel: "রাজ্য",
      districtLabel: "জেলা",
      experienceLabel: "অভিজ্ঞতার বছর",
      businessNameLabel: "ব্যবসা / কারিগরের নাম",
      aboutArtisanField: "কারিগর সম্পর্কে",
      saveProfileSuccess: "প্রোফাইল সফলভাবে আপডেট ও লোকাল স্টোরেজে সংরক্ষণ করা হয়েছে।",
      saveProfileError: "প্রোফাইল পরিবর্তন সংরক্ষণ করতে ব্যর্থ হয়েছে।",
      cancel: "বাতিল করুন",
      saveChanges: "পরিবর্তন সংরক্ষণ করুন"
    },
    addProduct: {
      step1Title: "ধাপ ১ — পণ্যের ছবি আপলোড করুন",
      step1Subtitle: "আপনার ফোনে ছবি তুলুন অথবা উচ্চমানের কারুশিল্প ছবি আপলোড করুন। কারিগর এআই ছবির আলো উন্নত করে ও স্বয়ংক্রিয়ভাবে সত্যতা যাচাই করে।",
      dragDropTitle: "পণ্যের ছবি টেনে এনে এখানে রাখুন",
      orText: "অথবা",
      clickToBrowse: "ফাইল ব্রাউজ করতে ক্লিক করুন",
      fromDevice: "আপনার কম্পিউটার বা ক্যামেরা থেকে",
      uploadFormats: "JPEG, PNG, WEBP সমর্থিত • সর্বোচ্চ ৫টি ছবি আপলোড করুন",
      sampleCraftsTitle: "অথবা পরীক্ষার জন্য খাঁটি কারুশিল্প নমুনা ছবি বাছুন:",
      verifiedCraftsBadge: "যাচাইকৃত ভারতীয় কারুশিল্প",
      giRegisteredBadge: "জিআই নিবন্ধিত",
      selectedImagesTitle: "নির্বাচিত পণ্যের ছবি:",
      primaryBadge: "প্রধান",
      step2Title: "ধাপ ২ — পণ্যের বিবরণ",
      step2Subtitle: "আপনার কারুশিল্পের বিবরণ লিখুন বা মাইক্রোফোন ব্যবহার করে স্বাভাবিকভাবে বলুন।",
      productNameLabel: "পণ্যের নাম *",
      productNamePlaceholder: "যেমন হস্তনির্মিত বাংলা পোড়ামাটির আলংকারিক পাত্র",
      categoryLabel: "বিভাগ *",
      catPottery: "মৃৎশিল্প ও সিরামিক",
      catBamboo: "বাঁশ ও বেতের কারুশিল্প",
      catWood: "দারুশিল্প ও খোদাই",
      catPainting: "লোকচিত্র ও শিল্প",
      catMetal: "ডোকরা ও পিতল ধাতুশিল্প",
      catHandloom: "তাঁত ও টেক্সটাইল",
      priceLabel: "মূল্য (₹) *",
      pricePlaceholder: "1099",
      materialLabel: "ব্যবহৃত উপাদান *",
      materialPlaceholder: "যেমন পলিমাটি সমৃদ্ধ পোড়ামাটি",
      stateRegionLabel: "রাজ্য / অঞ্চল *",
      stateRegionPlaceholder: "যেমন পশ্চিমবঙ্গ",
      craftTypeLabel: "কারুশিল্পের ধরন *",
      craftTypePlaceholder: "যেমন বাঁকুড়া পাঁচমুড়া মৃৎশিল্প",
      giTagLabel: "জিআই ট্যাগ যাচাইকরণ",
      govtCertified: "সরকারি প্রত্যয়িত",
      giNone: "কোনটি নয় / অন্যান্য ঐতিহ্যবাহী কারুশিল্প",
      stockLabel: "মজুত পরিমাণ *",
      stockPlaceholder: "15",
      descLabel: "পণ্যের বিবরণ *",
      descPlaceholder: "আপনার কারুশিল্প, অনুপ্রেরণা, পোড়ানোর পদ্ধতি, পরিমাপ ইত্যাদি বর্ণনা করুন...",
      backToImages: "ছবিতে ফিরে যান",
      proceedToAI: "এআই দিয়ে তৈরি করুন",
      aiStudioTitle: "কারিগর এআই ক্যাটালগ ও প্রামাণ্যতা স্টুডিও",
      aiStudioSubtitle: "কারুশিল্পের ছবি উন্নত করা, ন্যায্য মূল্য অনুমান এবং প্রামাণ্যতা সংকেত মূল্যায়ন।",
      allStepsComplete: "সমস্ত ৯টি প্রক্রিয়াকরণ ধাপ সম্পন্ন",
      aiProcessingMetadata: "এআই কারুশিল্পের মেটাডেটা বিশ্লেষণ করছে...",
      processingComplete: "প্রক্রিয়াকরণ সম্পন্ন",
      aiStepBackground: "পটভূমি অপসারণ",
      aiStepEnhance: "ছবি উন্নতকরণ",
      aiStepLighting: "আলোর ভারসাম্য উন্নতকরণ",
      aiStepAuthenticity: "ছবির সত্যতা যাচাই",
      aiStepTitle: "পণ্যের শিরোনাম তৈরি",
      aiStepDescription: "পণ্যের বিবরণ তৈরি",
      aiStepTranslating: "বিষয়বস্তু অনুবাদ",
      aiStepMarketPrice: "বাজার দর বিশ্লেষণ",
      aiStepSuggestedPrice: "প্রস্তাবিত মূল্য নির্ধারণ",
      catalogPreviewTitle: "এআই প্রস্তুত ক্যাটালগ প্রিভিউ",
      regenerate: "পুনরায় তৈরি করুন",
      edit: "সম্পাদনা",
      aiGenTitleLabel: "এআই প্রস্তুত শিরোনাম:",
      aiGenDescLabel: "এআই প্রস্তুত বিবরণ:",
      suggestedCategory: "প্রস্তাবিত বিভাগ:",
      material: "উপাদান:",
      origin: "উৎস:",
      marketPriceAnalysis: "বাজার দর পরিসীমা বিশ্লেষণ:",
      suggestedPriceLabel: "প্রস্তাবিত মূল্য:",
      recommendedPriceLabel: "সুপারিশকৃত তালিকা মূল্য:",
      acceptAISuggestions: "এআই পরামর্শ গ্রহণ ও পর্যালোচনা",
      authenticityCheckTitle: "পণ্য প্রামাণ্যতা পরীক্ষা",
      screenedBadge: "যাচাইকৃত",
      authenticityConfidence: "প্রামাণ্যতার আত্মবিশ্বাস স্তর",
      statusLikelyAuthentic: "স্থিতি: খাঁটি হওয়ার সম্ভাবনা বেশি ✓",
      sigAiImage: "এআই ছবি সনাক্তকরণ",
      sigAiImagePassed: "উত্তীর্ণ (প্রাকৃতিক)",
      sigDuplicate: "অনুরূপ ছবি পরীক্ষা",
      sigDuplicateMatches: "০ মিল (মৌলিক)",
      sigManipulation: "ছবি পরিবর্তন পরীক্ষা",
      sigManipulationClean: "পরিচ্ছন্ন (কোন সম্পাদনা নেই)",
      sigConsistency: "ছবি/পণ্য সঙ্গতি",
      sigConsistencyMatch: "৯৪% মিল",
      authenticityNote: "“ছবির সত্যতা যাচাই করতে একাধিক সংকেত ব্যবহার করা হয়। এআই সনাক্তকরণ সেন্সর প্যাটার্ন এবং প্রাকৃতিক আলোর প্রতিফলনের ওপর ভিত্তি করে ফলাফল দেয়।”",
      step4Title: "ধাপ ৪ — পর্যালোচনা ও প্রকাশনা",
      step4Subtitle: "আপনার চূড়ান্ত মার্কেটপ্লেস তালিকা, যাচাইকৃত শংসাপত্র ও এসক্রো সুরক্ষা বিবরণ পর্যালোচনা করুন।",
      readyForGlobalBuyers: "বিশ্বব্যাপী ক্রেতাদের জন্য প্রস্তুত",
      aiEnhancedLighting: "এআই উন্নত ও সুষম আলো",
      artisanPrefix: "কারিগর:",
      trustScoreValue: "বিশ্বাস স্কোর: ৪.৮ / ৫",
      unitsReadyWorkshop: "টি ইউনিট কর্মশালায় প্রস্তুত",
      craftStoryDetails: "কারুশিল্পের গল্প ও বিবরণ:",
      includedBadges: "অন্তর্ভুক্ত যাচাইকরণ ব্যাজ:",
      badgeIdentity: "পরিচয় যাচাইকৃত",
      badgeGI: "জিআই যাচাইকৃত (GI-452)",
      badgeImage: "প্রামাণিক ছবি (৯২%)",
      badgeCluster: "ক্লাস্টার যাচাইকৃত",
      badgeProcess: "প্রক্রিয়া প্রমাণ",
      backToAI: "এআই পরামর্শে ফিরে যান",
      saveAsDraft: "খসড়া হিসাবে সংরক্ষণ করুন",
      publishProduct: "পণ্য প্রকাশ করুন"
    }
  }
};

['en', 'hi', 'bn'].forEach(lang => {
  const filePath = path.join(__dirname, '..', 'src', 'i18n', `${lang}.json`);
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  const toMerge = additions[lang];
  
  for (const namespace in toMerge) {
    if (!data[namespace]) data[namespace] = {};
    for (const key in toMerge[namespace]) {
      data[namespace][key] = toMerge[namespace][key];
    }
  }

  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n', 'utf8');
  console.log(`Successfully merged additions to ${lang}.json`);
});
