const fs = require('fs');
const path = require('path');

const enPath = path.join(__dirname, '..', 'src', 'i18n', 'en.json');
const hiPath = path.join(__dirname, '..', 'src', 'i18n', 'hi.json');
const bnPath = path.join(__dirname, '..', 'src', 'i18n', 'bn.json');

const en = JSON.parse(fs.readFileSync(enPath, 'utf8'));
const hi = JSON.parse(fs.readFileSync(hiPath, 'utf8'));
const bn = JSON.parse(fs.readFileSync(bnPath, 'utf8'));

const newKeys = {
  en: {
    step2Title: "Step 2 — Product Details",
    step2Subtitle: "Enter your craft details or speak naturally using your microphone.",
    productName: "Product Name",
    productNamePlaceholder: "e.g. Handcrafted Bengal Terracotta Decorative Pot",
    category: "Category",
    catPottery: "Pottery & Ceramics",
    catBamboo: "Bamboo & Cane Craft",
    catWoodcraft: "Woodcraft & Carvings",
    catFolkPainting: "Folk Painting & Art",
    catMetalCraft: "Dhokra & Brass Metalwork",
    catHandloom: "Handloom & Textiles",
    priceLabel: "Price (₹)",
    materialLabel: "Material Used",
    materialPlaceholder: "e.g. Alluvial Terracotta Clay",
    stateLabel: "State / Region",
    statePlaceholder: "e.g. West Bengal",
    craftTypeLabel: "Craft Type",
    craftTypePlaceholder: "e.g. Bankura Panchmura Pottery",
    giTagVerification: "GI Tag Verification",
    govCertified: "Government Certified",
    giBankura: "Bankura Terracotta (GI-452)",
    giDhokra: "Bengal Dhokra (GI-564)",
    giMadhubani: "Madhubani Painting (GI-105)",
    giShantiniketan: "Shantiniketan Leather Goods (GI-86)",
    giNone: "None / Other Traditional Craft",
    stockLabel: "Stock Quantity",
    descLabel: "Product Description",
    descPlaceholder: "Describe your craft, inspiration, firing methods, dimensions...",
    studioTitle: "Karigar AI Catalog & Authenticity Studio",
    studioSubtitle: "Enhancing physical craft images, estimating fair artisan prices & evaluating authenticity signals.",
    allStepsComplete: "All 9 Processing Steps Complete",
    aiProcessingStatus: "AI Processing Craft Metadata...",
    processingCompleteStatus: "Processing Complete",
    aiStep1: "Analyzing uploaded craft image...",
    aiStep2: "Extracting color palette and textures...",
    aiStep3: "Generating artisan craft description...",
    aiStep4: "Cross-referencing GI Registry database...",
    aiStep5: "Calculating fair price estimate...",
    aiStep6: "Translating to 3 languages...",
    aiStep7: "Verifying physical authenticity signals...",
    aiStep8: "Optimizing image resolution & lighting...",
    aiStep9: "Ready for artisan final review",
    aiCatalogPreview: "AI Generated Catalog Preview",
    regenerate: "Regenerate",
    edit: "Edit",
    aiGenTitle: "AI Generated Title:",
    aiGenDesc: "AI Generated Description:",
    suggestedCat: "Suggested Category:",
    material: "Material:",
    origin: "Origin:",
    priceRangeAnalysis: "Market Price Range Analysis:",
    suggestedPriceLabel: "Suggested Price:",
    recommendedListingPrice: "Recommended Listing Price:",
    acceptAISuggestions: "Accept AI Suggestions & Review",
    authenticityCheckTitle: "Product Authenticity Check",
    screenedBadge: "Screened",
    authenticityConfidence: "Authenticity Confidence",
    statusLikelyAuthentic: "Status: Likely Authentic ✓",
    signalImageDetection: "AI Image Detection",
    signalPassedNatural: "Passed (Natural)",
    signalDuplicateCheck: "Duplicate Image Check",
    signal0MatchesOriginal: "0 Matches (Original)",
    signalManipulationCheck: "Image Manipulation Check",
    signalCleanNoEdits: "Clean (No Edits)",
    signalConsistency: "Image/Product Consistency",
    signal94Match: "94% Match",
    transparencyNote: "“Multiple signals are used to estimate image authenticity. AI detection estimates probability based on sensor patterns and physical light scattering.”",
    step4Title: "Step 4 — Review & Publish",
    step4Subtitle: "Inspect your final marketplace listing, verified credentials, and escrow protection details.",
    readyForBuyers: "Ready for Global Buyers",
    aiEnhancedLighting: "AI Enhanced & Lighting Normalized",
    artisanLabel: "Artisan:",
    trustScore: "Trust Score: 4.8 / 5",
    unitsInWorkshop: "{{count}} units ready in workshop",
    craftStoryLabel: "Craft Story & Details:",
    includedBadges: "Included Verification Badges:",
    badgeIdentityVerified: "Identity Verified",
    badgeGIVerified: "GI Verified (GI-452)",
    badgeAuthenticImage: "Authentic Image (92%)",
    badgeClusterVerified: "Cluster Verified",
    badgeProcessProof: "Process Proof",
    backToAI: "Back to AI Suggestions",
    saveDraft: "Save as Draft",
    publishButton: "Publish Product"
  },
  hi: {
    step2Title: "चरण 2 — उत्पाद विवरण",
    step2Subtitle: "अपने शिल्प का विवरण दर्ज करें या अपने माइक्रोफ़ोन से स्वाभाविक रूप से बोलें।",
    productName: "उत्पाद का नाम",
    productNamePlaceholder: "उदा. हस्तनिर्मित बंगाल टेराकोटा सजावटी बर्तन",
    category: "श्रेणी",
    catPottery: "मिट्टी के बर्तन और सिरेमिक",
    catBamboo: "बांस और बेंत शिल्प",
    catWoodcraft: "काष्ठ शिल्प और नक्काशी",
    catFolkPainting: "लोक चित्रकला और कला",
    catMetalCraft: "डोकरा और पीतल धातुशिल्प",
    catHandloom: "हथकरघा और वस्त्र",
    priceLabel: "मूल्य (₹)",
    materialLabel: "प्रयुक्त सामग्री",
    materialPlaceholder: "उदा. जलोढ़ टेराकोटा मिट्टी",
    stateLabel: "राज्य / क्षेत्र",
    statePlaceholder: "उदा. पश्चिम बंगाल",
    craftTypeLabel: "शिल्प का प्रकार",
    craftTypePlaceholder: "उदा. बांकुरा पंचमुरा मिट्टी के बर्तन",
    giTagVerification: "जीआई टैग सत्यापन",
    govCertified: "सरकारी प्रमाणित",
    giBankura: "बांकुरा टेराकोटा (GI-452)",
    giDhokra: "बंगाल डोकरा (GI-564)",
    giMadhubani: "मधुबनी पेंटिंग (GI-105)",
    giShantiniketan: "शांतिनिकेतन चमड़े का सामान (GI-86)",
    giNone: "कोई नहीं / अन्य पारंपरिक शिल्प",
    stockLabel: "स्टॉक मात्रा",
    descLabel: "उत्पाद विवरण",
    descPlaceholder: "अपने शिल्प, प्रेरणा, पकाने के तरीकों, आयामों का वर्णन करें...",
    studioTitle: "कारीगर एआई कैटलॉग और प्रमाणिकता स्टूडियो",
    studioSubtitle: "शिल्प चित्रों को बेहतर बनाना, कारीगरों के लिए उचित मूल्य का आकलन और प्रमाणिकता संकेतों का मूल्यांकन।",
    allStepsComplete: "सभी 9 प्रसंस्करण चरण पूर्ण",
    aiProcessingStatus: "एआई शिल्प मेटाडेटा संसाधित कर रहा है...",
    processingCompleteStatus: "प्रसंस्करण पूर्ण",
    aiStep1: "अपलोड की गई शिल्प छवि का विश्लेषण किया जा रहा है...",
    aiStep2: "रंग पैलेट और बनावट का निष्कर्षण किया जा रहा है...",
    aiStep3: "कारीगर शिल्प विवरण तैयार किया जा रहा है...",
    aiStep4: "जीआई रजिस्ट्री डेटाबेस से मिलान किया जा रहा है...",
    aiStep5: "उचित मूल्य अनुमान की गणना की जा रही है...",
    aiStep6: "3 भाषाओं में अनुवाद किया जा रहा है...",
    aiStep7: "शिल्प की भौतिक प्रमाणिकता संकेतों का सत्यापन...",
    aiStep8: "छवि रिज़ॉल्यूशन और रोशनी का अनुकूलन...",
    aiStep9: "कारीगर की अंतिम समीक्षा के लिए तैयार",
    aiCatalogPreview: "एआई द्वारा जनरेट कैटलॉग पूर्वावलोकन",
    regenerate: "पुनः जनरेट करें",
    edit: "संपादित करें",
    aiGenTitle: "एआई द्वारा जनरेट शीर्षक:",
    aiGenDesc: "एआई द्वारा जनरेट विवरण:",
    suggestedCat: "सुझाई गई श्रेणी:",
    material: "सामग्री:",
    origin: "मूल स्थान:",
    priceRangeAnalysis: "बाजार मूल्य सीमा विश्लेषण:",
    suggestedPriceLabel: "सुझाया गया मूल्य:",
    recommendedListingPrice: "अनुशंसित लिस्टिंग मूल्य:",
    acceptAISuggestions: "एआई सुझाव स्वीकार करें और समीक्षा करें",
    authenticityCheckTitle: "उत्पाद प्रमाणिकता जांच",
    screenedBadge: "जांचा गया",
    authenticityConfidence: "प्रमाणिकता विश्वास स्कोर",
    statusLikelyAuthentic: "स्थिति: संभवतः प्रामाणिक ✓",
    signalImageDetection: "एआई छवि पहचान",
    signalPassedNatural: "उत्तीर्ण (प्राकृतिक)",
    signalDuplicateCheck: "डुप्लिकेट छवि जांच",
    signal0MatchesOriginal: "0 मेल (मूल)",
    signalManipulationCheck: "छवि संपादन जांच",
    signalCleanNoEdits: "स्वच्छ (कोई संपादन नहीं)",
    signalConsistency: "छवि/उत्पाद संगति",
    signal94Match: "94% मेल",
    transparencyNote: "“छवि प्रमाणिकता का अनुमान लगाने के लिए कई संकेतों का उपयोग किया जाता है। एआई पहचान सेंसर पैटर्न और प्रकाश प्रकीर्णन के आधार पर संभावना का आकलन करती है।”",
    step4Title: "चरण 4 — समीक्षा करें और प्रकाशित करें",
    step4Subtitle: "अपनी अंतिम मार्केटप्लेस लिस्टिंग, सत्यापित क्रेडेंशियल्स और एस्क्रो सुरक्षा विवरण का निरीक्षण करें।",
    readyForBuyers: "वैश्विक खरीदारों के लिए तैयार",
    aiEnhancedLighting: "एआई संवर्धित और प्रकाश सामान्यीकृत",
    artisanLabel: "कारीगर:",
    trustScore: "विश्वास स्कोर: 4.8 / 5",
    unitsInWorkshop: "{{count}} इकाइयां कार्यशाला में तैयार हैं",
    craftStoryLabel: "शिल्प की कहानी और विवरण:",
    includedBadges: "शामिल सत्यापन बैज:",
    badgeIdentityVerified: "पहचान सत्यापित",
    badgeGIVerified: "जीआई सत्यापित (GI-452)",
    badgeAuthenticImage: "प्रामाणिक छवि (92%)",
    badgeClusterVerified: "क्लस्टर सत्यापित",
    badgeProcessProof: "प्रक्रिया प्रमाण",
    backToAI: "एआई सुझावों पर वापस जाएं",
    saveDraft: "ड्राफ्ट के रूप में सहेजें",
    publishButton: "उत्पाद प्रकाशित करें"
  },
  bn: {
    step2Title: "ধাপ ২ — পণ্যের বিবরণ",
    step2Subtitle: "আপনার হস্তশিল্পের বিবরণ লিখুন অথবা মাইক্রোফোন ব্যবহার করে স্বাভাবিকভাবে বলুন।",
    productName: "পণ্যের নাম",
    productNamePlaceholder: "যেমন হাতে তৈরি বাংলা টেরাকোটা আলংকারিক পাত্র",
    category: "বিভাগ",
    catPottery: "মৃৎশিল্প ও সিরামিক",
    catBamboo: "বাঁশ ও বেতের কাজ",
    catWoodcraft: "কাঠের কাজ ও খোদাই",
    catFolkPainting: "লোকচিত্র ও শিল্প",
    catMetalCraft: "ডোকরা ও পিতলের কাজ",
    catHandloom: "তাঁত ও বস্ত্র",
    priceLabel: "দাম (₹)",
    materialLabel: "ব্যবহৃত উপকরণ",
    materialPlaceholder: "যেমন পলিমাটির টেরাকোটা কাদামাটি",
    stateLabel: "রাজ্য / অঞ্চল",
    statePlaceholder: "যেমন পশ্চিমবঙ্গ",
    craftTypeLabel: "শিল্পের ধরন",
    craftTypePlaceholder: "যেমন বাঁকুড়া পাঁচমুড়া মৃৎশিল্প",
    giTagVerification: "জিআই ট্যাগ যাচাইকরণ",
    govCertified: "সরকারি প্রত্যয়িত",
    giBankura: "বাঁকুড়া টেরাকোটা (GI-452)",
    giDhokra: "বাংলা ডোকরা (GI-564)",
    giMadhubani: "মধুবনী চিত্রশিল্প (GI-105)",
    giShantiniketan: "শান্তিনিকেতন চামড়ার পণ্য (GI-86)",
    giNone: "কোনোটিই নয় / অন্যান্য ঐতিহ্যবাহী শিল্প",
    stockLabel: "মজুত পরিমাণ",
    descLabel: "পণ্যের বিবরণ",
    descPlaceholder: "আপনার শিল্প, অনুপ্রেরণা, তৈরির পদ্ধতি, মাপ ইত্যাদির বর্ণনা দিন...",
    studioTitle: "কারিগর এআই ক্যাটালগ ও প্রামাণিকতা স্টুডিও",
    studioSubtitle: "হস্তশিল্পের ছবি উন্নত করা, কারিগরদের ন্যায্য মূল্য নির্ধারণ এবং প্রামাণিকতার লক্ষণ মূল্যায়ন।",
    allStepsComplete: "সমস্ত ৯টি প্রক্রিয়াকরণ ধাপ সম্পন্ন",
    aiProcessingStatus: "এআই কারুশিল্প মেটাডেটা প্রক্রিয়া করছে...",
    processingCompleteStatus: "প্রক্রিয়াকরণ সম্পন্ন",
    aiStep1: "আপলোড করা কারুশিল্পের ছবি বিশ্লেষণ করা হচ্ছে...",
    aiStep2: "রঙের প্যালেট ও টেক্সচার নিষ্কাশন করা হচ্ছে...",
    aiStep3: "কারিগর শিল্পের বিবরণ তৈরি করা হচ্ছে...",
    aiStep4: "জিআই রেজিস্ট্রি ডেটাবেসের সাথে মেলানো হচ্ছে...",
    aiStep5: "ন্যায্য মূল্যের অনুমান গণনা করা হচ্ছে...",
    aiStep6: "৩টি ভাষায় অনুবাদ করা হচ্ছে...",
    aiStep7: "শারীরিক প্রামাণিকতার লক্ষণ যাচাই করা হচ্ছে...",
    aiStep8: "ছবির রেজোলিউশন ও আলোর মান উন্নত করা হচ্ছে...",
    aiStep9: "কারিগরদের চূড়ান্ত পর্যালোচনার জন্য প্রস্তুত",
    aiCatalogPreview: "এআই দ্বারা তৈরি ক্যাটালগ প্রিভিউ",
    regenerate: "পুনরায় তৈরি করুন",
    edit: "সম্পাদনা করুন",
    aiGenTitle: "এআই নির্মিত শিরোনাম:",
    aiGenDesc: "এআই নির্মিত বিবরণ:",
    suggestedCat: "প্রস্তাবিত বিভাগ:",
    material: "উপাদান:",
    origin: "উৎস:",
    priceRangeAnalysis: "বাজার মূল্যের সীমা বিশ্লেষণ:",
    suggestedPriceLabel: "প্রস্তাবিত মূল্য:",
    recommendedListingPrice: "সুপারিশকৃত তালিকা মূল্য:",
    acceptAISuggestions: "এআই পরামর্শ গ্রহণ করুন ও পর্যালোচনা করুন",
    authenticityCheckTitle: "পণ্য প্রামাণিকতা যাচাই",
    screenedBadge: "যাচাইকৃত",
    authenticityConfidence: "প্রামাণিকতা আত্মবিশ্বাস",
    statusLikelyAuthentic: "স্থিতি: প্রামাণিক হওয়ার সম্ভাবনা বেশি ✓",
    signalImageDetection: "এআই ছবি সনাক্তকরণ",
    signalPassedNatural: "উত্তীর্ণ (প্রাকৃতিক)",
    signalDuplicateCheck: "নকল ছবি পরীক্ষা",
    signal0MatchesOriginal: "০ মিল (আসল)",
    signalManipulationCheck: "ছবি সম্পাদনা পরীক্ষা",
    signalCleanNoEdits: "পরিচ্ছন্ন (কোনো পরিবর্তন নেই)",
    signalConsistency: "ছবি/পণ্যের সামঞ্জস্য",
    signal94Match: "৯৪% মিল",
    transparencyNote: "“ছবির প্রামাণিকতা অনুমানের জন্য একাধিক সংকেত ব্যবহার করা হয়। এআই সনাক্তকরণ সেন্সর প্যাটার্ন এবং শারীরিক আলোর বিচ্ছুরণের উপর ভিত্তি করে সম্ভাব্যতা গণনা করে।”",
    step4Title: "ধাপ ৪ — পর্যালোচনা ও প্রকাশ করুন",
    step4Subtitle: "আপনার চূড়ান্ত মার্কেটপ্লেস তালিকা, যাচাইকৃত তথ্য এবং এসক্রো সুরক্ষা বিবরণ পর্যালোচনা করুন।",
    readyForBuyers: "বিশ্বব্যাপী ক্রেতাদের জন্য প্রস্তুত",
    aiEnhancedLighting: "এআই পরিমার্জিত ও আলো স্বাভাবিকীকৃত",
    artisanLabel: "কারিগর:",
    trustScore: "ট্রাস্ট স্কোর: ৪.৮ / ৫",
    unitsInWorkshop: "কর্মশালায় {{count}}টি একক প্রস্তুত রয়েছে",
    craftStoryLabel: "কারুশিল্পের গল্প ও বিবরণ:",
    includedBadges: "অন্তর্ভুক্ত যাচাইকরণ ব্যাজ:",
    badgeIdentityVerified: "পরিচয় যাচাইকৃত",
    badgeGIVerified: "জিআই যাচাইকৃত (GI-452)",
    badgeAuthenticImage: "প্রামাণিক ছবি (৯২%)",
    badgeClusterVerified: "ক্লাস্টার যাচাইকৃত",
    badgeProcessProof: "প্রক্রিয়া প্রমাণ",
    backToAI: "এআই পরামর্শে ফিরে যান",
    saveDraft: "খসড়া হিসেবে সংরক্ষণ করুন",
    publishButton: "পণ্য প্রকাশ করুন"
  }
};

en.addProduct = Object.assign({}, en.addProduct, newKeys.en);
hi.addProduct = Object.assign({}, hi.addProduct, newKeys.hi);
bn.addProduct = Object.assign({}, bn.addProduct, newKeys.bn);

fs.writeFileSync(enPath, JSON.stringify(en, null, 2), 'utf8');
fs.writeFileSync(hiPath, JSON.stringify(hi, null, 2), 'utf8');
fs.writeFileSync(bnPath, JSON.stringify(bn, null, 2), 'utf8');

console.log('Successfully merged all AddProduct keys for en, hi, bn!');
